import { Work_Sans } from 'next/font/google';
import { getColorScheme } from '@/features/color-scheme/get-color-scheme';
import { UserDropdownMenu } from '@/features/user/user-dropdown-menu';

import './globals.css';

const workSans = Work_Sans({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const colorScheme = getColorScheme();

  return (
    <html
      lang="en"
      className={workSans.className}
      data-color-scheme={colorScheme}
    >
      <body className="min-h-[100dvh] bg-gray1 text-gray12 transition-colors">
        <div className="mx-auto grid max-w-prose grid-rows-[auto_1fr_auto] border-x border-solid border-gray6">
          <header className="sticky top-0 flex min-h-[4rem] items-center justify-between border-b border-solid border-gray6 bg-gray1 px-4 py-2">
            <h1 className="text-3xl font-bold">WARD</h1>
            <UserDropdownMenu colorScheme={colorScheme} />
          </header>
          <main className="px-4 py-2">{children}</main>
          <footer className="flex min-h-[4rem] items-center justify-center border-t border-solid border-gray6 bg-gray2">
            <small className="text-gray11">&copy; Mykyta Batrak 2023</small>
          </footer>
        </div>
      </body>
    </html>
  );
}
